FROM debian:9.5-slim

ADD entrypoint.sh /entrypoint.sh
ADD sfdx-linux-x64.tar.gz /work/ #automaticamente descomprime el tar.gz
# RUN tar xzvf /work/sfdx-linux-x64.tar.gz -C /work
RUN chmod +x /entrypoint.sh
# ENTRYPOINT ["/entrypoint.sh"]


